#!/bin/bash
# isto acima e uma shebang, onde a palavra 'bash' poderia ser substituida por 'zsh' para especificar shell de uso

# variaveis
padrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
roxo="\033[0;35m"
ciano="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
roxoClaro="\033[1;35m"
cianoClaro="\033[1;36m"
branco="\033[1;37m"
fundoPreto="\033[40;1;37m"
fundoVermelho="\033[41;1;37m"
fundoVerde="\033[42;1;37m"
fundoAmarelo="\033[43;1;37m"
fundoAzul="\033[44;1;37m"
fundoRoxo="\033[45;1;37m"
fundoCiano="\033[46;1;37m"
fundoBranco="\033[47;1;37m"
estiloSublinhado="\033[4;30m"
estiloPiscando="\033[5;30m"
estiloInvertido="\033[7;30m"
estiloOculto="\033[8;30m"

echo "Imprimindo cores"

echo -e " ${padrao} Padrão ${padrao} \t\t\t --> 0 "
echo -e " ${preto} Preto ${padrao} \t\t\t --> 0;30 "
echo -e " ${vermelho} Vermelho ${padrao} \t\t\t --> 0;31 "
echo -e " ${verde} Verde ${padrao} \t\t\t --> 0;32 "
echo -e " ${marrom} Marrom ${padrao} \t\t\t --> 0;33 "
echo -e " ${azul} Azul ${padrao} \t\t\t --> 0;34 "
echo -e " ${roxo} Roxo ${padrao} \t\t\t --> 0;35 "
echo -e " ${ciano} Ciano ${padrao} \t\t\t --> 0;36 "
echo -e " ${cinzaClaro} Cinza Claro ${padrao} \t\t\t --> 0;37 "
echo -e " ${pretoCinza} Preto Acinzentado ${padrao} \t\t --> 1;30 "
echo -e " ${vermelhoClaro} Vermelho Claro ${padrao} \t\t --> 1;31 "
echo -e " ${verdeClaro} Verde Claro ${padrao} \t\t\t --> 1;32 "
echo -e " ${amarelo} Amarelo ${padrao} \t\t\t --> 1;33 "
echo -e " ${azulClaro} Azul Claro ${padrao} \t\t\t --> 1;34 "
echo -e " ${roxoClaro} Roxo Claro ${padrao} \t\t\t --> 1;35 "
echo -e " ${cianoClaro} Ciano Claro ${padrao} \t\t\t --> 1;36 "
echo -e " ${branco} Branco ${padrao} \t\t\t --> 1;37 "

echo -e " ${fundoPreto} Fundo Preto ${padrao} \t\t\t --> 40;?;? "
echo -e " ${fundoVermelho} Fundo Vermelho ${padrao} \t\t --> 41;?;? "
echo -e " ${fundoVerde} Fundo Verde ${padrao} \t\t\t --> 42;?;? "
echo -e " ${fundoAmarelo} Fundo Amarelo ${padrao} \t\t --> 43;?;? "
echo -e " ${fundoAzul} Fundo Azul ${padrao} \t\t\t --> 44;?;? "
echo -e " ${fundoRoxo} Fundo Roxo ${padrao} \t\t\t --> 45;?;? "
echo -e " ${fundoCiano} Fundo Ciano ${padrao} \t\t\t --> 46;?;? "
echo -e " ${fundoBranco} Fundo Branco ${padrao} \t\t --> 47;?;? "

echo -e " ${estiloSublinhado} Sublinhado ${padrao} \t\t\t --> 4;? "
echo -e " ${estiloPiscando} Piscando ${padrao} \t\t\t --> 5;? "
echo -e " ${estiloInvertido} Invertido ${padrao} \t\t\t --> 7;? "
echo -e " ${estiloOculto} Oculto ${padrao} \t\t\t --> 8;? " 

